package com.example.model.wp;

public class EmbeddedCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedded_category.keyword
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column embedded_category.category
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedded_category.keyword
     *
     * @return the value of embedded_category.keyword
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedded_category.keyword
     *
     * @param keyword the value for embedded_category.keyword
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column embedded_category.category
     *
     * @return the value of embedded_category.category
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column embedded_category.category
     *
     * @param category the value for embedded_category.category
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_category
     *
     * @mbggenerated Sun Nov 01 12:34:26 PST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keyword=").append(keyword);
        sb.append(", category=").append(category);
        sb.append("]");
        return sb.toString();
    }
}