package com.example.model.wp;

import java.util.Date;

public class WpPosts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.ID
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_author
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Long postAuthor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_date
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Date postDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_date_gmt
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Date postDateGmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String postStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.comment_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String commentStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.ping_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String pingStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_password
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String postPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_name
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_modified
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Date postModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_modified_gmt
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Date postModifiedGmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_parent
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Long postParent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.guid
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.menu_order
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Integer menuOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_type
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String postType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_mime_type
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private String postMimeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.comment_count
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	private Long commentCount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.ID
	 * @return  the value of wp_posts.ID
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.ID
	 * @param id  the value for wp_posts.ID
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_author
	 * @return  the value of wp_posts.post_author
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Long getPostAuthor() {
		return postAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_author
	 * @param postAuthor  the value for wp_posts.post_author
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostAuthor(Long postAuthor) {
		this.postAuthor = postAuthor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_date
	 * @return  the value of wp_posts.post_date
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Date getPostDate() {
		return postDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_date
	 * @param postDate  the value for wp_posts.post_date
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_date_gmt
	 * @return  the value of wp_posts.post_date_gmt
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Date getPostDateGmt() {
		return postDateGmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_date_gmt
	 * @param postDateGmt  the value for wp_posts.post_date_gmt
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostDateGmt(Date postDateGmt) {
		this.postDateGmt = postDateGmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_status
	 * @return  the value of wp_posts.post_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getPostStatus() {
		return postStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_status
	 * @param postStatus  the value for wp_posts.post_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostStatus(String postStatus) {
		this.postStatus = postStatus == null ? null : postStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.comment_status
	 * @return  the value of wp_posts.comment_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getCommentStatus() {
		return commentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.comment_status
	 * @param commentStatus  the value for wp_posts.comment_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setCommentStatus(String commentStatus) {
		this.commentStatus = commentStatus == null ? null : commentStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.ping_status
	 * @return  the value of wp_posts.ping_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getPingStatus() {
		return pingStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.ping_status
	 * @param pingStatus  the value for wp_posts.ping_status
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPingStatus(String pingStatus) {
		this.pingStatus = pingStatus == null ? null : pingStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_password
	 * @return  the value of wp_posts.post_password
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getPostPassword() {
		return postPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_password
	 * @param postPassword  the value for wp_posts.post_password
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostPassword(String postPassword) {
		this.postPassword = postPassword == null ? null : postPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_name
	 * @return  the value of wp_posts.post_name
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_name
	 * @param postName  the value for wp_posts.post_name
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostName(String postName) {
		this.postName = postName == null ? null : postName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_modified
	 * @return  the value of wp_posts.post_modified
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Date getPostModified() {
		return postModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_modified
	 * @param postModified  the value for wp_posts.post_modified
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostModified(Date postModified) {
		this.postModified = postModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_modified_gmt
	 * @return  the value of wp_posts.post_modified_gmt
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Date getPostModifiedGmt() {
		return postModifiedGmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_modified_gmt
	 * @param postModifiedGmt  the value for wp_posts.post_modified_gmt
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostModifiedGmt(Date postModifiedGmt) {
		this.postModifiedGmt = postModifiedGmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_parent
	 * @return  the value of wp_posts.post_parent
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Long getPostParent() {
		return postParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_parent
	 * @param postParent  the value for wp_posts.post_parent
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostParent(Long postParent) {
		this.postParent = postParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.guid
	 * @return  the value of wp_posts.guid
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.guid
	 * @param guid  the value for wp_posts.guid
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.menu_order
	 * @return  the value of wp_posts.menu_order
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Integer getMenuOrder() {
		return menuOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.menu_order
	 * @param menuOrder  the value for wp_posts.menu_order
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setMenuOrder(Integer menuOrder) {
		this.menuOrder = menuOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_type
	 * @return  the value of wp_posts.post_type
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getPostType() {
		return postType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_type
	 * @param postType  the value for wp_posts.post_type
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostType(String postType) {
		this.postType = postType == null ? null : postType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_mime_type
	 * @return  the value of wp_posts.post_mime_type
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public String getPostMimeType() {
		return postMimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_mime_type
	 * @param postMimeType  the value for wp_posts.post_mime_type
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setPostMimeType(String postMimeType) {
		this.postMimeType = postMimeType == null ? null : postMimeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.comment_count
	 * @return  the value of wp_posts.comment_count
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public Long getCommentCount() {
		return commentCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.comment_count
	 * @param commentCount  the value for wp_posts.comment_count
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	public void setCommentCount(Long commentCount) {
		this.commentCount = commentCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 22:04:52 PDT 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", postAuthor=").append(postAuthor);
		sb.append(", postDate=").append(postDate);
		sb.append(", postDateGmt=").append(postDateGmt);
		sb.append(", postStatus=").append(postStatus);
		sb.append(", commentStatus=").append(commentStatus);
		sb.append(", pingStatus=").append(pingStatus);
		sb.append(", postPassword=").append(postPassword);
		sb.append(", postName=").append(postName);
		sb.append(", postModified=").append(postModified);
		sb.append(", postModifiedGmt=").append(postModifiedGmt);
		sb.append(", postParent=").append(postParent);
		sb.append(", guid=").append(guid);
		sb.append(", menuOrder=").append(menuOrder);
		sb.append(", postType=").append(postType);
		sb.append(", postMimeType=").append(postMimeType);
		sb.append(", commentCount=").append(commentCount);
		sb.append("]");
		return sb.toString();
	}
}