package com.example.model.wp;

import java.util.Calendar;

import com.example.util.WpUpdaterUtils;

public class WpPostsWithBLOBs extends WpPosts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_content
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private String postContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_title
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private String postTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_excerpt
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private String postExcerpt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.to_ping
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private String toPing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.pinged
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private String pinged;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_posts.post_content_filtered
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private String postContentFiltered;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_content
	 * @return  the value of wp_posts.post_content
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public String getPostContent() {
		return postContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_content
	 * @param postContent  the value for wp_posts.post_content
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setPostContent(String postContent) {
		this.postContent = postContent == null ? null : postContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_title
	 * @return  the value of wp_posts.post_title
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public String getPostTitle() {
		return postTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_title
	 * @param postTitle  the value for wp_posts.post_title
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle == null ? null : postTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_excerpt
	 * @return  the value of wp_posts.post_excerpt
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public String getPostExcerpt() {
		return postExcerpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_excerpt
	 * @param postExcerpt  the value for wp_posts.post_excerpt
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setPostExcerpt(String postExcerpt) {
		this.postExcerpt = postExcerpt == null ? null : postExcerpt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.to_ping
	 * @return  the value of wp_posts.to_ping
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public String getToPing() {
		return toPing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.to_ping
	 * @param toPing  the value for wp_posts.to_ping
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setToPing(String toPing) {
		this.toPing = toPing == null ? null : toPing.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.pinged
	 * @return  the value of wp_posts.pinged
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public String getPinged() {
		return pinged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.pinged
	 * @param pinged  the value for wp_posts.pinged
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setPinged(String pinged) {
		this.pinged = pinged == null ? null : pinged.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_posts.post_content_filtered
	 * @return  the value of wp_posts.post_content_filtered
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public String getPostContentFiltered() {
		return postContentFiltered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_posts.post_content_filtered
	 * @param postContentFiltered  the value for wp_posts.post_content_filtered
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setPostContentFiltered(String postContentFiltered) {
		this.postContentFiltered = postContentFiltered == null ? null : postContentFiltered.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", postContent=").append(postContent);
		sb.append(", postTitle=").append(postTitle);
		sb.append(", postExcerpt=").append(postExcerpt);
		sb.append(", toPing=").append(toPing);
		sb.append(", pinged=").append(pinged);
		sb.append(", postContentFiltered=").append(postContentFiltered);
		sb.append("]");
		return sb.toString();
	}

	public WpPostsWithBLOBs() {
		setPostAuthor(1L);
		setPostDate(Calendar.getInstance().getTime());
		setPostDateGmt(WpUpdaterUtils.getCurrentUtcTime());
		setPostExcerpt("");
		setCommentStatus(WpUpdaterUtils.CONST_COMMENT_STATUS_CLOSED);
		setPingStatus(WpUpdaterUtils.CONST_COMMENT_STATUS_CLOSED);
		setPostPassword("");
		setPostModified(getPostDate());
		setPostModifiedGmt(getPostDateGmt());
		setToPing("");
		setPinged("");
		setPostContentFiltered("");
		setMenuOrder(0);
		setCommentCount(0L);
		setGuid("");
		setPostMimeType("");
	}
}