package com.example.model.wp;

public class WpTermRelationshipsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_term_relationships.object_id
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private Long objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wp_term_relationships.term_taxonomy_id
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	private Long termTaxonomyId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_term_relationships.object_id
	 * @return  the value of wp_term_relationships.object_id
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public Long getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_term_relationships.object_id
	 * @param objectId  the value for wp_term_relationships.object_id
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wp_term_relationships.term_taxonomy_id
	 * @return  the value of wp_term_relationships.term_taxonomy_id
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public Long getTermTaxonomyId() {
		return termTaxonomyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wp_term_relationships.term_taxonomy_id
	 * @param termTaxonomyId  the value for wp_term_relationships.term_taxonomy_id
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	public void setTermTaxonomyId(Long termTaxonomyId) {
		this.termTaxonomyId = termTaxonomyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Thu Oct 29 22:05:09 PDT 2015
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", objectId=").append(objectId);
		sb.append(", termTaxonomyId=").append(termTaxonomyId);
		sb.append("]");
		return sb.toString();
	}
}