package com.example.mapper;

import com.example.model.wp.EmbeddedTag;
import com.example.model.wp.EmbeddedTagCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmbeddedTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int countByExample(EmbeddedTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int deleteByExample(EmbeddedTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int deleteByPrimaryKey(String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int insert(EmbeddedTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int insertSelective(EmbeddedTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    List<EmbeddedTag> selectByExampleWithRowbounds(EmbeddedTagCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    List<EmbeddedTag> selectByExample(EmbeddedTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    EmbeddedTag selectByPrimaryKey(String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int updateByExampleSelective(@Param("record") EmbeddedTag record, @Param("example") EmbeddedTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int updateByExample(@Param("record") EmbeddedTag record, @Param("example") EmbeddedTagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int updateByPrimaryKeySelective(EmbeddedTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table embedded_tag
     *
     * @mbggenerated Thu Oct 29 22:05:09 PDT 2015
     */
    int updateByPrimaryKey(EmbeddedTag record);
}