package com.example.mapper;

import com.example.model.wp.WpPostmeta;
import com.example.model.wp.WpPostmetaCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WpPostmetaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int countByExample(WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int deleteByExample(WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int deleteByPrimaryKey(Long metaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int insert(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int insertSelective(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	List<WpPostmeta> selectByExampleWithBLOBsWithRowbounds(WpPostmetaCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	List<WpPostmeta> selectByExampleWithBLOBs(WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	List<WpPostmeta> selectByExampleWithRowbounds(WpPostmetaCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	List<WpPostmeta> selectByExample(WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	WpPostmeta selectByPrimaryKey(Long metaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int updateByExampleSelective(@Param("record") WpPostmeta record, @Param("example") WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") WpPostmeta record, @Param("example") WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int updateByExample(@Param("record") WpPostmeta record, @Param("example") WpPostmetaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int updateByPrimaryKeySelective(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int updateByPrimaryKeyWithBLOBs(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sun Oct 18 22:17:31 PDT 2015
	 */
	int updateByPrimaryKey(WpPostmeta record);
}