package com.example.mapper;

import com.example.model.WpPostmeta;
import com.example.model.WpPostmetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WpPostmetaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int countByExample(WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByExample(WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByPrimaryKey(Long metaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insert(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insertSelective(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpPostmeta> selectByExampleWithBLOBs(WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpPostmeta> selectByExample(WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	WpPostmeta selectByPrimaryKey(Long metaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleSelective(@Param("record") WpPostmeta record, @Param("example") WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") WpPostmeta record, @Param("example") WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExample(@Param("record") WpPostmeta record, @Param("example") WpPostmetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeySelective(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeyWithBLOBs(WpPostmeta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKey(WpPostmeta record);
}