package com.example.mapper;

import com.example.model.WpPosts;
import com.example.model.WpPostsExample;
import com.example.model.WpPostsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WpPostsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int countByExample(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByExample(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insert(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insertSelective(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpPostsWithBLOBs> selectByExampleWithBLOBs(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpPosts> selectByExample(WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	WpPostsWithBLOBs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleSelective(@Param("record") WpPostsWithBLOBs record, @Param("example") WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") WpPostsWithBLOBs record, @Param("example") WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExample(@Param("record") WpPosts record, @Param("example") WpPostsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeySelective(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeyWithBLOBs(WpPostsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_posts
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKey(WpPosts record);
}