package com.example.mapper;

import com.example.model.WpTermTaxonomy;
import com.example.model.WpTermTaxonomyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WpTermTaxonomyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int countByExample(WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByExample(WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByPrimaryKey(Long termTaxonomyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insert(WpTermTaxonomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insertSelective(WpTermTaxonomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpTermTaxonomy> selectByExampleWithBLOBs(WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpTermTaxonomy> selectByExample(WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	WpTermTaxonomy selectByPrimaryKey(Long termTaxonomyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleSelective(@Param("record") WpTermTaxonomy record, @Param("example") WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") WpTermTaxonomy record, @Param("example") WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExample(@Param("record") WpTermTaxonomy record, @Param("example") WpTermTaxonomyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeySelective(WpTermTaxonomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeyWithBLOBs(WpTermTaxonomy record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_taxonomy
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKey(WpTermTaxonomy record);
}