package com.example.mapper;

import com.example.model.WpTermRelationships;
import com.example.model.WpTermRelationshipsExample;
import com.example.model.WpTermRelationshipsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WpTermRelationshipsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int countByExample(WpTermRelationshipsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByExample(WpTermRelationshipsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByPrimaryKey(WpTermRelationshipsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insert(WpTermRelationships record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insertSelective(WpTermRelationships record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpTermRelationships> selectByExample(WpTermRelationshipsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	WpTermRelationships selectByPrimaryKey(WpTermRelationshipsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleSelective(@Param("record") WpTermRelationships record, @Param("example") WpTermRelationshipsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExample(@Param("record") WpTermRelationships record, @Param("example") WpTermRelationshipsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeySelective(WpTermRelationships record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_term_relationships
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKey(WpTermRelationships record);
}