package com.example.mapper;

import com.example.model.wp.WpTerms;
import com.example.model.wp.WpTermsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WpTermsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int countByExample(WpTermsCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int deleteByExample(WpTermsCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int deleteByPrimaryKey(Long termId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int insert(WpTerms record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int insertSelective(WpTerms record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	List<WpTerms> selectByExampleWithRowbounds(WpTermsCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	List<WpTerms> selectByExample(WpTermsCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	WpTerms selectByPrimaryKey(Long termId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int updateByExampleSelective(@Param("record") WpTerms record, @Param("example") WpTermsCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int updateByExample(@Param("record") WpTerms record, @Param("example") WpTermsCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int updateByPrimaryKeySelective(WpTerms record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sun Nov 01 12:34:26 PST 2015
	 */
	int updateByPrimaryKey(WpTerms record);
}