package com.example.mapper;

import com.example.model.WpTerms;
import com.example.model.WpTermsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WpTermsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int countByExample(WpTermsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByExample(WpTermsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int deleteByPrimaryKey(Long termId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insert(WpTerms record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int insertSelective(WpTerms record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	List<WpTerms> selectByExample(WpTermsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	WpTerms selectByPrimaryKey(Long termId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExampleSelective(@Param("record") WpTerms record, @Param("example") WpTermsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByExample(@Param("record") WpTerms record, @Param("example") WpTermsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKeySelective(WpTerms record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_terms
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	int updateByPrimaryKey(WpTerms record);
}