package com.example.model;

import java.util.ArrayList;
import java.util.List;

public class WpPostmetaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public WpPostmetaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMetaIdIsNull() {
			addCriterion("meta_id is null");
			return (Criteria) this;
		}

		public Criteria andMetaIdIsNotNull() {
			addCriterion("meta_id is not null");
			return (Criteria) this;
		}

		public Criteria andMetaIdEqualTo(Long value) {
			addCriterion("meta_id =", value, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdNotEqualTo(Long value) {
			addCriterion("meta_id <>", value, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdGreaterThan(Long value) {
			addCriterion("meta_id >", value, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdGreaterThanOrEqualTo(Long value) {
			addCriterion("meta_id >=", value, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdLessThan(Long value) {
			addCriterion("meta_id <", value, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdLessThanOrEqualTo(Long value) {
			addCriterion("meta_id <=", value, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdIn(List<Long> values) {
			addCriterion("meta_id in", values, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdNotIn(List<Long> values) {
			addCriterion("meta_id not in", values, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdBetween(Long value1, Long value2) {
			addCriterion("meta_id between", value1, value2, "metaId");
			return (Criteria) this;
		}

		public Criteria andMetaIdNotBetween(Long value1, Long value2) {
			addCriterion("meta_id not between", value1, value2, "metaId");
			return (Criteria) this;
		}

		public Criteria andPostIdIsNull() {
			addCriterion("post_id is null");
			return (Criteria) this;
		}

		public Criteria andPostIdIsNotNull() {
			addCriterion("post_id is not null");
			return (Criteria) this;
		}

		public Criteria andPostIdEqualTo(Long value) {
			addCriterion("post_id =", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotEqualTo(Long value) {
			addCriterion("post_id <>", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdGreaterThan(Long value) {
			addCriterion("post_id >", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdGreaterThanOrEqualTo(Long value) {
			addCriterion("post_id >=", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdLessThan(Long value) {
			addCriterion("post_id <", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdLessThanOrEqualTo(Long value) {
			addCriterion("post_id <=", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdIn(List<Long> values) {
			addCriterion("post_id in", values, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotIn(List<Long> values) {
			addCriterion("post_id not in", values, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdBetween(Long value1, Long value2) {
			addCriterion("post_id between", value1, value2, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotBetween(Long value1, Long value2) {
			addCriterion("post_id not between", value1, value2, "postId");
			return (Criteria) this;
		}

		public Criteria andMetaKeyIsNull() {
			addCriterion("meta_key is null");
			return (Criteria) this;
		}

		public Criteria andMetaKeyIsNotNull() {
			addCriterion("meta_key is not null");
			return (Criteria) this;
		}

		public Criteria andMetaKeyEqualTo(String value) {
			addCriterion("meta_key =", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyNotEqualTo(String value) {
			addCriterion("meta_key <>", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyGreaterThan(String value) {
			addCriterion("meta_key >", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyGreaterThanOrEqualTo(String value) {
			addCriterion("meta_key >=", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyLessThan(String value) {
			addCriterion("meta_key <", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyLessThanOrEqualTo(String value) {
			addCriterion("meta_key <=", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyLike(String value) {
			addCriterion("meta_key like", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyNotLike(String value) {
			addCriterion("meta_key not like", value, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyIn(List<String> values) {
			addCriterion("meta_key in", values, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyNotIn(List<String> values) {
			addCriterion("meta_key not in", values, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyBetween(String value1, String value2) {
			addCriterion("meta_key between", value1, value2, "metaKey");
			return (Criteria) this;
		}

		public Criteria andMetaKeyNotBetween(String value1, String value2) {
			addCriterion("meta_key not between", value1, value2, "metaKey");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wp_postmeta
	 * @mbggenerated  Sat Oct 17 17:42:36 PDT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wp_postmeta
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 17 17:27:09 PDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}